crypto:
  - BTC/USD
  - ETH/USD
  - SOL/USD
  - LINK/USD
  - ARB/USD
  - ATOM/USD
  - AVAX/USD
  - BNB/USD
  - DOGE/USD
  - DOT/USD
  - LTC/USD
  - POL/USD
  - OP/USD
  - TRX/USD
  - UNI/USD
  - XRP/USD

stocks:
  - SPY
  - AAPL
  - MSFT
