name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint (flake8)
        run: |
          flake8 .

      - name: Format check (black)
        run: |
          black --check .

      - name: Test (pytest)
        env:
          # Ensure no accidental network-heavy ops
          TB_NO_TELEGRAM: '1'
        run: |
          pytest -q


